### ISSUE TITLE
Ctrl and network in one

### ISSUE THREAD

**Issue by nordge1** [romilgupta/openstack-juno-scripts#1]
Just a question, is there  away to install ctrl and network in one box? Or maybe I don't even need network. All i want is for my VM's to share same addressing as LAN.

**Comment by romilgupta** [comment]
Yeah, you can do it.

On Sat, Sep 6, 2014 at 7:56 AM, nordge1 notifications@github.com wrote:

> Just a question, is there away to install ctrl and network in one box?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/romilgupta/openstack-juno-scripts/issues/1.

## 

_Regards,_

*Romil *

**Comment by nordge1** [comment]
How would you go about doing that? Do I just run the ctrl and network script on the same box?
